### PR TITLE
Fix the delegate

### PR DESCRIPTION
**Pull request by elizabethcd**
Changes the delegate for the 1.6.9 update https://stardewvalleywiki.com/Modding:Migrate_to_Stardew_Valley_1.6.9#ForEachItem_changes

Really sorry about the line endings, I am not sure how to tell Github to knock it off. The actual changes are lines 82-105.

### CODE REVIEW

**Comment by greyivy** [comment]
Thanks a bunch for this! Will get it merged and released shortly.

The whitespace diff toggle is here :)
image

**Comment by greyivy** [comment]
Did you manage to get this to build? `ForEachItemContext` doesn't seem to exist...

**Comment by elizabethcd** [comment]
Yes, it built for me — I did directly copy paste the part I changed and edit it back in on Github in a browser, but that's the only difference. I can attached the built copy if that helps? Is it possible your game and/or SMAPI hasn't updated yet?
[Ornithologists Guild.zip](https://github.com/user-attachments/files/17637367/Ornithologists.Guild.zip)

**Comment by greyivy** [comment]
That was it! The game itself was out of date. Thank you :)

**Pull request merged**
